source 'http://gitlab.quvideo.com/Pods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

use_modular_headers!

#消除多源pod警告
install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => true, :warn_for_multiple_pod_sources => false

target 'HelloWorld_Example' do
  eval(File.open('PodDevExtension.rb').read) if File.exist? 'PodDevExtension.rb'
  # 对commit-msg进行hook，规范commit提交
  `cp .././commit-msg ../.git/hooks/` unless File.exist? '../.git/hooks/commit-msg'
  pod 'HelloWorld', :path => '../'

  target 'HelloWorld_Tests' do
    inherit! :search_paths

    
  end
end
